/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bdd.automation.api.teste;

import bdd.automation.api.dominio.Usuario;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class TesteUsuario extends TesteBase {

    private static final String LISTA_USUARIOS_ENDPOINT = "/users";
    private static final String CRIA_USUARIOS_ENDPOINT = "/user";

    @Test
    public void testeMostraPaginaEspecifica() {
        given().
                params("page","2").
        when().
                get(LISTA_USUARIOS_ENDPOINT).
        then().
               statusCode(HttpStatus.SC_OK).
               body("page",is(2)).
               body("data",is(notNullValue()));
    }

    @Test
    public void testeCriaUsuarioComSucesso(){
        Usuario usuario = new Usuario("Michel","Analista","email@gmail.com");
        given().
                body(usuario).
                when().
                post(CRIA_USUARIOS_ENDPOINT).
                then().
                statusCode(HttpStatus.SC_CREATED).
                body("name",is("Michel"));
    }
}
