/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bdd.automation.api.teste;

import bdd.automation.api.dominio.Usuario;
import io.restassured.RestAssured;
import io.restassured.builder.RequestSpecBuilder;
import io.restassured.builder.ResponseSpecBuilder;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.HashMap;
import java.util.Map;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.assertThat;

public class TesteUsuarioSemRestAssured {

    private static final String BASE_URL = "https://reqres.in";
    private static final String BASE_PATH = "/api";
    private static final String LISTA_USUARIOS_ENDPOINT = "/users";
    private static final String CRIA_USUARIOS_ENDPOINT = "/user";
    private static final String MOSTRAR_USUARIO_ENDPOINT = "/users/{userID}";

    @BeforeClass
    public static void setup(){
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
    }

    @Test
    public void testeMostraPaginaEspecifica() {
        String uri = getUri(LISTA_USUARIOS_ENDPOINT);

        given().
                params("page", "2").
                when().
                get(uri).
                then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }



    @Test
    public void testeCriaUsuarioComSucesso() {
        String uri = getUri(CRIA_USUARIOS_ENDPOINT);

        Map<String, String> usuario = new HashMap<>();
        usuario.put("name", "Michel");
        usuario.put("job", "Analista");
        given().
                contentType(ContentType.JSON).
                body(usuario).
                when().
                post(uri).
                then().
                statusCode(HttpStatus.SC_CREATED).
                body("name", is("Michel"));
    }

    @Test
    public void testeTamanhoDosItensMostradosIgualAoPerPage() {
        String uri = getUri(LISTA_USUARIOS_ENDPOINT);
        int paginaEsperada = 2;
        int perPageEsperado = retornaPerPageEsperado(paginaEsperada);
        given().
                params("page", paginaEsperada).
                when().
                get(uri).
                then().
                statusCode(HttpStatus.SC_OK).
                body(
                        "page", is(paginaEsperada),
                        "data.size()", is(perPageEsperado),
                        "data.findAll {it.avatar.startsWith('https://reqres.in/')}.size()", is(perPageEsperado)
                );
    }

    @Test
    public void testeMostraUsuarioEspecifico() {
        String uri = getUri(MOSTRAR_USUARIO_ENDPOINT);
        Usuario usuario = given().
                pathParam("userID", 2).
                when().
                get(uri).
                then().
                statusCode(HttpStatus.SC_OK).
                extract().
                body().jsonPath().getObject("data", Usuario.class);

        assertThat(usuario.getEmail(), containsString("@reqres.in"));
        assertThat(usuario.getName(), is("Janet"));
//        assertThat(usuario.getLastName(),is("Weaver"));

    }

    private static int retornaPerPageEsperado(int page) {
        String uri = getUri(LISTA_USUARIOS_ENDPOINT);
        int perPageEsperado = given()
                .param("page", page)
                .when()
                .get(uri)
                .then()
                .statusCode(HttpStatus.SC_OK)
                .extract()
                .path("per_page");
        return perPageEsperado;
    }

    private static String getUri(String endpoint) {
        String uri = BASE_URL + BASE_PATH + endpoint;
        return uri;
    }
}
