/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bdd.automation.api.teste;

import bdd.automation.api.dominio.Usuario;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.BeforeClass;
import org.junit.Test;

import static io.restassured.RestAssured.*;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.hamcrest.CoreMatchers.is;

public class UsuarioTest {

    @BeforeClass
    public static void setup(){
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        baseURI = "https://reqres.in/";
        basePath = "/api";
    }

    @Test
    public void testListaMetadadosDoUsuario() {
        given().
                params("page","2").
        when().
                get("/users").
        then().
               statusCode(HttpStatus.SC_OK).
               body("page",is(2)).
               body("data",is(notNullValue()));
    }

    @Test
    public void testCriaUsuarioComSucesso(){
        Usuario usuario = new Usuario("Michel","Analista");
        given().
                contentType(ContentType.JSON).
                body(usuario).
                when().
                post("/users").
                then().
                statusCode(HttpStatus.SC_CREATED).
                body("name",is("Michel"));
    }
}
