/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bdd.automation.api.teste;

import bdd.automation.api.dominio.Usuario;
import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Test;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;

public class UsuarioTest extends BaseTest{

    @Test
    public void testListaMetadadosDoUsuario() {
        given().
                params("page","2").
        when().
                get("/users").
        then().
               statusCode(HttpStatus.SC_OK).
               body("page",is(2)).
               body("data",is(notNullValue()));
    }

    @Test
    public void testCriaUsuarioComSucesso(){
        Usuario usuario = new Usuario("Michel","Analista","email@gmail.com");
        given().
                body(usuario).
                when().
                post("/users").
                then().
                statusCode(HttpStatus.SC_CREATED).
                body("name",is("Michel"));
    }
}
